### ISSUE TITLE
feat: add `timeout` option for `.expect` API

### ISSUE THREAD

**Issue by tony-go** [tony-go/clix#17]
## Context

In some cases, the CLI program could take more than 500 ms (default timeout) to output something in the console.

We'd like to have an option for the `.expect` API to customize the timeout.

```js
const scenario_1 = clix('my command')
  .expect('Hey user, what is your name?')
  .input('tony')
  .expect('Super!', { timeout: 3000 });
```

## Acceptance criteria
* the `timeout` option should only affect the act itself (not other acts)
* in case of custom timeout we should log something for debug mode
* if the output is available before the timeout we don't want to wait for it

**Comment by Maestro31** [comment]
@tony-go , i would like to take this issue ;) .

How do we handle the api when the argument is an array of values? Should we add a timeout option per array value or a global timeout?

```js
const scenario_1 = clix('my command')
  .expect('Hey user, what is your name?')
  .input('tony')
  .expect([
    ['Super!', { timeout: 3000 }],
    ['Oh yeah!', { timeout: 3000 }],
    ['Oh yeah again!', { timeout: 3000 }],
  ]);
```

Or

```js
const scenario_1 = clix('my command')
  .expect('Hey user, what is your name?')
  .input('tony')
  .expect(['Super!', 'Oh yeah!', 'Oh yeah again!'], { timeout: 3000 });
```

Another idea ?
